### ISSUE TITLE
DOQ to use Anycast servers

### ISSUE THREAD

**Issue by dnses** [nextdns/diag#16]
Hi,  I'm a subscriber and I'm trying to use anycast servers for my DOQ.
how do I prepend anycast to the DOQ URL with my nextdns profile?

it works when I write "quic://Device'sname-myNEXTDNS-ID.dns.nextdns.io": uses my Nextdns profile but does not go to anycast.

or "quic://anycast.dns1.nextdns.io" also works using the anycast server but does not use my Configured NextDNS profile.

But I want to append anycast so that I can use DOQ with the anycast servers and my nextDNS ID at the same time. Please, How do I write this?

**Comment by rs** [comment]
Please use https://help.nextdns.io for questions not related to the CLI.

About your question, you can’t force anycast and pass an id, this is not supported. In general it is a bad idea to force anycast. May I ask why you’d want to do that?

**Comment by dnses** [comment]
how do I pay up front using the cryptocurrency method? What happens if I click restart subscription and I pay again? Will the new renewal be added so that the older number of months left is added to the new subscription?






On Thursday, July 27, 2023 at 10:51:54 AM EDT, Olivier Poitrey ***@***.***> wrote: 







Please use https://help.nextdns.io for questions not related to the CLI.

About your question, you can’t force anycast and pass an id, this is not supported. In general it is a bad idea to force anycast. May I ask why you’d want to do that?
