### ISSUE TITLE
Couldn't download 

### ISSUE THREAD

**Issue by QAInsights** [nextdns/diag#2]
In the latest version of Edge, when I try to download the diag.exe file, I am getting below error. Could you please check this issue? Thanks!

![QAInsights-0051](https://user-images.githubusercontent.com/2826376/99489872-aea5b400-2936-11eb-94a3-87d1658f0adf.jpg)

**Comment by rs** [comment]
Isn’t there a way to force the download anyway?

**Comment by QAInsights** [comment]
Yes @rs I could do that, but Virus Detected message scares me :). Also, if I scan the exe file using Microsoft Defender, it is showing Threads detected. Is it normal?

**Comment by rs** [comment]
The binary us not signed, that’s probably why. You can ignore, it’s a false positive

**Comment by QAInsights** [comment]
Thanks. Closing this issue.
