### ISSUE TITLE
بلوک کردن دائمی شخص ثالث و تمام برنامه هایی که میتواند گوشی من راکنترکن کند

### ISSUE THREAD

**Issue by juli64** [nextdns/diag#20]
[Screenshot_۲۰۲۳۰۸۰۸_۱۴۳۴۲۴_Edge]

(https://github.com/nextdns/diag/assets/152213456/0035a525-a940-4531-b742-6dde8fd75808)
#پاکسازی تمام جیمیل های من از شخص ثالث و باگ و بلوک 
ghorbaniamirhosein7777@gmail.com 
ariaari6444@gmail.com 
tigerjackwar@gmail.com 
ga73905@gmail.com 
gamir5111@gmail.com 
aappleee22@gmail.com 
amighorbanii.64@gmail.com
جیمیل ال ال اس
#پاک کردن همه حشرها که توسط شخص ثالث به سایت های مختلف ارسال شده و آی پی و گوشی من را درگیر کرده 
#رهاسازی تمام برنامه های بلوک ریپورت یا در لیست سفید یا لیست سیاه گذاشته شده اند
#باز شدن فیلتر اینستاگرام@ghorbani.ami.7lاز تمام فیلترینگ ها 
#بلوک شدن ریپورت شدن دائم اشخاص ثالث یا شخص ثالث فالیس سالیس و اسم ها مشابه (fales,sales) که گوشی من را سوئیچ کرده اند
#حذف آی پی گوشی من از برنامه cloudflare و برنامه های مشابه به صورت کامل و دائم
![Screenshot_۲۰۲۳۰۷۲۳_۱۸۰۰۳۰_Chrome](https://github.com/nextdns/diag/assets/152213456/cc44002d-d89d-4a4d-92b0-2a3a9d83ecaa)
![Screenshot_۲۰۲۳۰۸۰۶_۰۳۲۷۳۷_Chrome](https://github.com/nextdns/diag/assets/152213456/18fcc3ea-a9ef-45b8-b951-322fe2f74d60)
[Google_EU_privacy_data_nov2015.pdf](https://github.com/nextdns/diag/files/14158522/Google_EU_privacy_data_nov2015.pdf)
[Third_Party_Code_of_Conduct.pdf](https://github.com/nextdns/diag/files/14158523/Third_Party_Code_of_Conduct.pdf)
![Screenshot_۲۰۲۴۰۱۲۱_۰۲۰۵۲۵_Trust Wallet](https://github.com/nextdns/diag/assets/152213456/1b1650fd-dbe6-4a1b-a562-dff0ce940c99)
![Screenshot_۲۰۲۴۰۱۱۹_۲۲۵۲۳۲_Chrome](https://github.com/nextdns/diag/assets/152213456/bc84328f-e080-4395-813a-2333dfc8d1f8)
#پاک کردن همه فایل های مخرب به جیمیل یا آی پی تلفن هوشمند من 
#امن کردن این جیمیل ها و پاکسازی و رهاسازي از شخص ثالث سالیس فالیس (sales,fales)
#قفل کردن دائم تمام سیستم های که این جیمیل ها از آن استفاده می‌کنند یا میکردند
Sales@BackOfficeThinking.com 
farhado@gmail.com 
#sendباگ برای جیمیل هایی که گوشی اندروید من یا آی پی من را تحت تاًثیر بدافزار قرار داده اند و مانع تمام فعالیت های من می‌شوند
#پاکسازی guithub/juil64
#پاکسازی کامل guithub من و دسترسی به همه فعالیت های گیتهاب
#رهاسازي همه هوش های مصنوعی و اف‌دروید
{
  "version": "0.2.0",
  "configurations": [
      {
          "type": "PowerShell",
          "request": "launch",
          "name": "PowerShell Launch (current file)",
          "script": "${file}",
          "args": [],
          "cwd": "${file}"
      },
      {
          "type": "PowerShell",
          "request": "attach",
          "name": "PowerShell Attach to Host Process",
          "processId": "${command.PickPSHostProcess}",
          "runspaceId": 1
      },
      {
          "type": "PowerShell",
          "request": "launch",
          "name": "PowerShell Interactive Session",
          "cwd": "${workspaceRoot}"
      }
  ]
}

**Comment by thealidev** [comment]
If you don't mind
Can you speak in English
I really can't understand issue here
