### ISSUE TITLE
Starting TV makes internet unreachable for all devices

### ISSUE THREAD

**Issue by PetFra** [nextdns/diag#29]
Hi, I use NextDNS on Ubiquiti Dream Machine. Since 5 days ago I noticed when I turned on the TV internet disappear for all the devices, Dream Machine shows no internet connection with my ISP.

I opened a ticket with Unifi support, they suggested to try uninstalling the additional package so I did and the issue disappeared.
So i used NextDNS diagnostic tool to generate the file attached. The issue appeared whetever I use Eth or WiFi connection.
The television is a LG one, if it may help.

Thanks for your help

[diag_1.1.zip](https://github.com/nextdns/diag/files/15192325/diag_1.1.zip)

**Comment by rs** [comment]
Please open a discussion on https://help.nextdns.io. Also, post the resulting diag URL provided after submission, not the binary. You can find the instructions on https://nextdns.io/diag.
