### ISSUE TITLE
Post unsuccessful: Post "http://localhost:8081/diagnostic": dial tcp [::1]:8081: connect: connection refused

### ISSUE THREAD

**Issue by thatguy12223** [nextdns/diag#5]
Marks-Work-Mac-Mini:rolling_update markyang$ sh -c 'sh -c "$(curl -sL https://nextdns.io/diag)"'

Welcome to NextDNS network diagnostic tool.

This tool will download a small binary to capture latency and routing information
regarding the connectivity of your network with NextDNS. In order to perform a
traceroute, root permission is required. You may therefore be asked to provide
your password for sudo.

The source code of this tool is available at https://github.com/nextdns/diag

Do you want to continue? (press enter to accept)
Testing IPv6 connectivity
  available: false
Fetching https://test.nextdns.io
  status: ok
  client: 116.86.57.141
  protocol: UDP
  dest IP: 45.90.30.28
  server: anexia-fra-1
Traceroute for primary IPv4 (45.90.28.0)
    1    192.168.0.1    0ms   0ms   0ms
    2    183.90.60.1    2ms   2ms   2ms
    3  183.90.44.117    2ms   2ms   4ms
    4   183.90.44.45    2ms   2ms   2ms
    5  203.118.6.201    5ms   5ms   3ms
    6  203.118.4.136    3ms   2ms   2ms
    7 103.137.13.169    3ms   2ms   2ms
    8  103.137.13.27    2ms   2ms   2ms
    9  103.137.13.18    2ms   2ms   3ms
   10     45.90.28.0    2ms   3ms   2ms
Traceroute for secondary IPv4 (45.90.30.0)
    1    192.168.0.1    0ms   0ms   0ms
    2    183.90.60.1    2ms   2ms   3ms
    3   183.90.44.61    3ms   2ms   2ms
    4   183.90.44.41    2ms   2ms   5ms
    5   203.118.3.65    2ms   4ms   *
    6   203.118.6.25    2ms   3ms   3ms
    7  203.117.35.78    3ms   3ms   2ms
    8   203.118.6.33    3ms   3ms   2ms
    9  203.118.12.46    3ms   3ms   2ms
   10 80.249.213.102  167ms 167ms 167ms
   11 144.208.208.156  165ms 165ms 165ms
   12 144.208.208.211  173ms 173ms 174ms
   13     45.90.30.0  173ms 173ms 173ms
Fetching PoP name for primary IPv4 (45.90.28.0)
  gsl-sin: 291.2µs
Fetching PoP name for secondary IPv4 (45.90.30.0)
  anexia-fra: 16.5505ms
Pinging PoPs
  rix-sin: 330.4µs
  gsl-sin: 400µs
  vultr-sin: 354.4µs
  anexia-sin: 364.8µs
  anexia-hkg: 3.8874ms
  rix-hkg: 3.9498ms
  gsl-per: 4.9ms
  ls-pnq: 6.0459ms
  rix-tpe: 6.7ms
Do you want to send this report? [Y/n]: Y
Optional email in case we need additional info: markyangzw@gmail.com
Post unsuccessful: Post "http://localhost:8081/diagnostic": dial tcp [::1]:8081: connect: connection refused
Marks-Work-Mac-Mini:rolling_update markyang$

**Comment by rs** [comment]
Fixed, thx for the heads up
