### ISSUE TITLE
Windows Defender classifies binary as high security risk

### ISSUE THREAD

**Issue by eikaramba** [nextdns/diag#6]
Title says it all. That does not to seem to be a signing issue.
![grafik](https://user-images.githubusercontent.com/1320525/100256760-74936e00-2f45-11eb-980f-a9639e2ad07c.png)

**Comment by s-crypt** [comment]
![image](https://user-images.githubusercontent.com/41712656/100979237-5e168500-34f8-11eb-9c70-f8ad9fcc8b86.png)

I submitted it as a false positive to microsoft and they seem to have cleared it.

@rs I will keep doing so with each release if/as they keep happening, but I believe that this current issue can be closed.

**Comment by rs** [comment]
Thx
